//! Render the schema IR as Rust source.
//!
//! Output is committed to the repository rather than produced by a build script: builds
//! stay reproducible and fast for downstream users, docs.rs works, and a schema change
//! shows up as a reviewable diff.

use anyhow::{Context, Result, bail};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::ir::{AttrKind, Class, Multiplicity, Name, Primitive, Schema};

pub fn emit(schema: &Schema, out_dir: &Path, check: bool) -> Result<()> {
    let vintage_dir = out_dir.join(&schema.vintage);
    let files: Vec<(String, String)> = vec![
        ("mod.rs".to_owned(), emit_mod(schema)),
        ("tables.rs".to_owned(), emit_tables(schema)?),
        ("names.rs".to_owned(), emit_names(schema)),
        ("views.rs".to_owned(), emit_views(schema)),
    ]
    .into_iter()
    .map(|(name, src)| (name, rustfmt(&src)))
    .collect();

    if check {
        let mut stale = Vec::new();
        for (name, content) in &files {
            let path = vintage_dir.join(name);
            let current = std::fs::read_to_string(&path).unwrap_or_default();
            if normalize(&current) != normalize(content) {
                stale.push(path.display().to_string());
            }
        }
        let root = out_dir.join("mod.rs");
        let expected_root = rustfmt(&emit_root(schema));
        if normalize(&std::fs::read_to_string(&root).unwrap_or_default())
            != normalize(&expected_root)
        {
            stale.push(root.display().to_string());
        }
        if !stale.is_empty() {
            bail!(
                "generated sources are stale:\n  {}\nRun `cargo xtask codegen`.",
                stale.join("\n  ")
            );
        }
        println!("generated sources are up to date");
        return Ok(());
    }

    std::fs::create_dir_all(&vintage_dir)
        .with_context(|| format!("creating {}", vintage_dir.display()))?;
    for (name, content) in &files {
        let path = vintage_dir.join(name);
        std::fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
        println!("wrote {} ({} bytes)", path.display(), content.len());
    }
    let root = out_dir.join("mod.rs");
    std::fs::write(&root, rustfmt(&emit_root(schema)))?;
    println!("wrote {}", root.display());
    Ok(())
}

/// Ignore line-ending and trailing-whitespace differences when comparing.
fn normalize(s: &str) -> String {
    s.lines().map(str::trim_end).collect::<Vec<_>>().join("\n")
}

/// Format generated source with the workspace's rustfmt settings.
///
/// Generated code is committed and reviewed like any other source, so it is formatted
/// the same way. This also keeps `cargo fmt --check` and `cargo xtask codegen --check`
/// from contradicting each other in CI. If rustfmt is unavailable the unformatted source
/// is returned rather than failing the build.
fn rustfmt(src: &str) -> String {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let spawned = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout", "--quiet"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn();
    let Ok(mut child) = spawned else {
        eprintln!("warning: rustfmt not found; emitting unformatted source");
        return src.to_owned();
    };
    if let Some(mut stdin) = child.stdin.take() {
        // A broken pipe here means rustfmt rejected the input; the wait below reports it.
        let _ = stdin.write_all(src.as_bytes());
    }
    match child.wait_with_output() {
        Ok(out) if out.status.success() => {
            String::from_utf8(out.stdout).unwrap_or_else(|_| src.to_owned())
        }
        _ => {
            eprintln!("warning: rustfmt failed; emitting unformatted source");
            src.to_owned()
        }
    }
}

const HEADER: &str = "\
// @generated by `cargo xtask codegen` from the CIM/CGMES RDFS vocabularies.
// Do not edit by hand; edit the generator and regenerate.
//
// The RDFS vocabularies this file is derived from are published by ENTSO-E and the
// UCA International Users Group under the Apache License 2.0.
";

fn emit_root(schema: &Schema) -> String {
    let v = &schema.vintage;
    format!(
        "{HEADER}
//! Generated CIM schema vintages.

pub mod {v};
"
    )
}

fn emit_mod(schema: &Schema) -> String {
    let v = &schema.vintage;
    let title = match v.as_str() {
        "cgmes3" => "CGMES 3.0 (IEC TS 61970-600-1/-2:2021)",
        other => other,
    };
    format!(
        "{HEADER}
//! {title}.
//!
//! Generated from the ENTSO-E application profile vocabularies. [`SCHEMA`] is the entry
//! point; [`names`] gives compile-time constants for every class and attribute, and
//! [`views`] provides typed accessors.

mod tables;

pub mod names;
pub mod views;

pub use tables::SCHEMA;
pub use names::{{classes, attributes, enums, profiles}};
"
    )
}

// ---------------------------------------------------------------------------
// Static tables
// ---------------------------------------------------------------------------

fn emit_tables(schema: &Schema) -> Result<String> {
    let ns_index: BTreeMap<&str, usize> = schema
        .namespaces
        .keys()
        .enumerate()
        .map(|(i, ns)| (ns.as_str(), i))
        .collect();
    let class_index: BTreeMap<&Name, usize> = schema
        .classes
        .keys()
        .enumerate()
        .map(|(i, n)| (n, i))
        .collect();
    let enum_index: BTreeMap<&Name, usize> = schema
        .enums
        .keys()
        .enumerate()
        .map(|(i, n)| (n, i))
        .collect();
    let dt_index: BTreeMap<&Name, usize> = schema
        .datatypes
        .keys()
        .enumerate()
        .map(|(i, n)| (n, i))
        .collect();

    // Attributes get a single flat table; every class refers to them by index.
    let mut attr_rows: Vec<(&Name, &Class, &crate::ir::Attribute)> = Vec::new();
    for class in schema.classes.values() {
        for a in &class.attributes {
            attr_rows.push((&a.name, class, a));
        }
    }
    attr_rows.sort_by(|a, b| a.0.cmp(b.0));
    let attr_index: BTreeMap<&Name, usize> = attr_rows
        .iter()
        .enumerate()
        .map(|(i, (n, _, _))| (*n, i))
        .collect();

    let mut enum_value_rows: Vec<(&Name, usize, &crate::ir::EnumValue)> = Vec::new();
    for (ei, e) in schema.enums.values().enumerate() {
        for v in &e.values {
            enum_value_rows.push((&v.name, ei, v));
        }
    }
    enum_value_rows.sort_by(|a, b| a.0.cmp(b.0));
    let enum_value_index: BTreeMap<&Name, usize> = enum_value_rows
        .iter()
        .enumerate()
        .map(|(i, (n, _, _))| (*n, i))
        .collect();

    if attr_rows.len() > u16::MAX as usize || schema.classes.len() > u16::MAX as usize {
        bail!("schema exceeds the u16 id space");
    }

    let mut s = String::with_capacity(4 << 20);
    s.push_str(HEADER);
    s.push_str(
        "
#![allow(clippy::all)]

use crate::schema::*;

",
    );

    // Namespaces.
    writeln!(s, "static NAMESPACES: &[NamespaceDef] = &[").unwrap();
    for (ns, prefix) in &schema.namespaces {
        writeln!(
            s,
            "    NamespaceDef {{ iri: {}, prefix: {} }},",
            quote(ns),
            quote(prefix)
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    // Profiles.
    writeln!(s, "static PROFILES: &[ProfileDef] = &[").unwrap();
    for p in &schema.profiles {
        writeln!(
            s,
            "    ProfileDef {{ keyword: {}, version_iri: {}, title: {} }},",
            quote(&p.keyword),
            quote(&p.version_iri),
            quote(&p.title)
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    // Per-class attribute id slices.
    for (ci, class) in schema.classes.values().enumerate() {
        let own: Vec<String> = class
            .attributes
            .iter()
            .map(|a| format!("AttrId({})", attr_index[&a.name]))
            .collect();
        writeln!(s, "static OWN_{ci}: &[AttrId] = &[{}];", own.join(", ")).unwrap();

        let all: Vec<String> = schema
            .all_attributes(&class.name)
            .iter()
            .map(|(_, a)| format!("AttrId({})", attr_index[&a.name]))
            .collect();
        writeln!(s, "static ALL_{ci}: &[AttrId] = &[{}];", all.join(", ")).unwrap();

        let anc: Vec<String> = schema
            .ancestors(&class.name)
            .iter()
            .map(|c| format!("ClassId({})", class_index[&c.name]))
            .collect();
        writeln!(s, "static ANC_{ci}: &[ClassId] = &[{}];", anc.join(", ")).unwrap();
    }
    s.push('\n');

    // Classes.
    writeln!(s, "static CLASSES: &[ClassDef] = &[").unwrap();
    for (ci, class) in schema.classes.values().enumerate() {
        let parent = match &class.parent {
            Some(p) => format!("Some(ClassId({}))", class_index[p]),
            None => "None".to_owned(),
        };
        writeln!(
            s,
            "    ClassDef {{ name: {}, ns: NsId({}), parent: {parent}, concrete: {}, \
             profiles: {}, deprecated: {}, own_attrs: OWN_{ci}, all_attrs: ALL_{ci}, \
             ancestors: ANC_{ci}, doc: {} }},",
            quote(&class.name.local),
            ns_index[class.name.ns.as_str()],
            class.concrete,
            class.profiles,
            class.deprecated,
            quote(class.comment.as_deref().unwrap_or(""))
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    // Attributes.
    writeln!(s, "static ATTRIBUTES: &[AttrDef] = &[").unwrap();
    for (name, owner, a) in &attr_rows {
        let kind = match &a.kind {
            AttrKind::Primitive(p) => format!("AttrKind::Primitive({})", primitive(*p)),
            AttrKind::Datatype(d) => match dt_index.get(d) {
                Some(i) => format!("AttrKind::Datatype(DatatypeId({i}))"),
                None => "AttrKind::Primitive(Primitive::String)".to_owned(),
            },
            AttrKind::Enumeration(e) => match enum_index.get(e) {
                Some(i) => format!("AttrKind::Enumeration(EnumId({i}))"),
                None => "AttrKind::Primitive(Primitive::String)".to_owned(),
            },
            AttrKind::Association {
                target, inverse, ..
            } => {
                let Some(t) = class_index.get(target) else {
                    // Target outside the vintage: degrade to an opaque reference rather
                    // than dropping the attribute.
                    continue;
                };
                let inv = inverse
                    .as_ref()
                    .and_then(|i| attr_index.get(i))
                    .map(|i| format!("Some(AttrId({i}))"))
                    .unwrap_or_else(|| "None".to_owned());
                format!("AttrKind::Association {{ target: ClassId({t}), inverse: {inv} }}")
            }
        };
        // Plain attributes are always serialized where they exist; only associations
        // distinguish a used from a derived side.
        let used_in = match &a.kind {
            AttrKind::Association { used_in, .. } => *used_in,
            _ => a.profiles,
        };
        let fixed = match &a.fixed {
            Some(f) => format!("Some({})", quote(f)),
            None => "None".to_owned(),
        };
        writeln!(
            s,
            "    AttrDef {{ name: {}, label: {}, ns: NsId({}), owner: ClassId({}), \
             kind: {kind}, mult: {}, profiles: {}, used_in: {used_in}, deprecated: {}, \
             fixed: {fixed}, doc: {} }},",
            quote(&name.local),
            quote(&a.label),
            ns_index[name.ns.as_str()],
            class_index[&owner.name],
            mult(a.multiplicity),
            a.profiles,
            a.deprecated,
            quote(a.comment.as_deref().unwrap_or(""))
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    // Enumerations.
    for (ei, e) in schema.enums.values().enumerate() {
        let vals: Vec<String> = e
            .values
            .iter()
            .map(|v| format!("EnumValueId({})", enum_value_index[&v.name]))
            .collect();
        writeln!(
            s,
            "static ENUM_VALS_{ei}: &[EnumValueId] = &[{}];",
            vals.join(", ")
        )
        .unwrap();
    }
    s.push('\n');

    writeln!(s, "static ENUMS: &[EnumDef] = &[").unwrap();
    for (ei, e) in schema.enums.values().enumerate() {
        writeln!(
            s,
            "    EnumDef {{ name: {}, ns: NsId({}), profiles: {}, values: ENUM_VALS_{ei}, doc: {} }},",
            quote(&e.name.local),
            ns_index[e.name.ns.as_str()],
            e.profiles,
            quote(e.comment.as_deref().unwrap_or(""))
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    writeln!(s, "static ENUM_VALUES: &[EnumValueDef] = &[").unwrap();
    for (name, owner, v) in &enum_value_rows {
        writeln!(
            s,
            "    EnumValueDef {{ name: {}, label: {}, ns: NsId({}), owner: EnumId({owner}), doc: {} }},",
            quote(&name.local),
            quote(&v.label),
            ns_index[name.ns.as_str()],
            quote(v.comment.as_deref().unwrap_or(""))
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    // Datatypes.
    writeln!(s, "static DATATYPES: &[DatatypeDef] = &[").unwrap();
    for d in schema.datatypes.values() {
        writeln!(
            s,
            "    DatatypeDef {{ name: {}, ns: NsId({}), value: {}, unit: {}, multiplier: {}, doc: {} }},",
            quote(&d.name.local),
            ns_index[d.name.ns.as_str()],
            primitive(d.value),
            opt_quote(d.unit.as_deref()),
            opt_quote(d.multiplier.as_deref()),
            quote(d.comment.as_deref().unwrap_or(""))
        )
        .unwrap();
    }
    s.push_str("];\n\n");

    // Lookup indexes, sorted by (namespace index, name) to allow binary search.
    let mut cidx: Vec<(usize, &str, usize)> = schema
        .classes
        .keys()
        .enumerate()
        .map(|(i, n)| (ns_index[n.ns.as_str()], n.local.as_str(), i))
        .collect();
    cidx.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(b.1)));
    writeln!(s, "static CLASS_INDEX: &[(u16, &str, ClassId)] = &[").unwrap();
    for (ns, name, id) in cidx {
        writeln!(s, "    ({ns}, {}, ClassId({id})),", quote(name)).unwrap();
    }
    s.push_str("];\n\n");

    let mut aidx: Vec<(usize, &str, usize)> = attr_rows
        .iter()
        .enumerate()
        .map(|(i, (n, _, _))| (ns_index[n.ns.as_str()], n.local.as_str(), i))
        .collect();
    aidx.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(b.1)));
    writeln!(s, "static ATTR_INDEX: &[(u16, &str, AttrId)] = &[").unwrap();
    for (ns, name, id) in aidx {
        writeln!(s, "    ({ns}, {}, AttrId({id})),", quote(name)).unwrap();
    }
    s.push_str("];\n\n");

    let mut eidx: Vec<(usize, &str, usize)> = enum_value_rows
        .iter()
        .enumerate()
        .map(|(i, (n, _, _))| (ns_index[n.ns.as_str()], n.local.as_str(), i))
        .collect();
    eidx.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(b.1)));
    writeln!(
        s,
        "static ENUM_VALUE_INDEX: &[(u16, &str, EnumValueId)] = &["
    )
    .unwrap();
    for (ns, name, id) in eidx {
        writeln!(s, "    ({ns}, {}, EnumValueId({id})),", quote(name)).unwrap();
    }
    s.push_str("];\n\n");

    writeln!(
        s,
        "static SCHEMA_DATA: Schema = Schema {{
    vintage: {},
    namespaces: NAMESPACES,
    profiles: PROFILES,
    classes: CLASSES,
    attributes: ATTRIBUTES,
    enums: ENUMS,
    enum_values: ENUM_VALUES,
    datatypes: DATATYPES,
    class_index: CLASS_INDEX,
    attr_index: ATTR_INDEX,
    enum_value_index: ENUM_VALUE_INDEX,
}};

/// The {} schema.
pub static SCHEMA: &Schema = &SCHEMA_DATA;",
        quote(&schema.vintage),
        schema.vintage
    )
    .unwrap();

    Ok(s)
}

// ---------------------------------------------------------------------------
// Named constants
// ---------------------------------------------------------------------------

fn emit_names(schema: &Schema) -> String {
    let mut s = String::with_capacity(1 << 20);
    s.push_str(HEADER);
    s.push_str(
        "
//! Compile-time identifiers for every schema element.
//!
//! Using these instead of string lookups makes model code both faster and
//! typo-proof: a renamed class becomes a compile error rather than a runtime `None`.

#![allow(non_upper_case_globals, non_snake_case)]

use crate::schema::{AttrId, ClassId, EnumId, EnumValueId, ProfileId};

/// Profiles of this vintage.
pub mod profiles {
    use super::ProfileId;
",
    );
    for (i, p) in schema.profiles.iter().enumerate() {
        let ident = rust_const(&p.keyword);
        writeln!(
            s,
            "    /// `{}` — {}\n    pub const {ident}: ProfileId = ProfileId({i});",
            p.keyword,
            escape_doc(&p.title)
        )
        .unwrap();
    }
    s.push_str("}\n\n/// Classes of this vintage.\npub mod classes {\n    use super::ClassId;\n");
    for (i, c) in schema.classes.values().enumerate() {
        let ident = rust_const(&c.name.local);
        writeln!(
            s,
            "    /// `{}`{}\n    pub const {ident}: ClassId = ClassId({i});",
            c.name.local,
            if c.concrete { "" } else { " (abstract)" }
        )
        .unwrap();
    }
    s.push_str("}\n\n");

    // Attributes are grouped per class so names stay unambiguous.
    s.push_str("/// Attributes, grouped by declaring class.\npub mod attributes {\n    use super::AttrId;\n");
    let mut rows: Vec<(&Name, usize)> = Vec::new();
    {
        let mut all: Vec<&Name> = Vec::new();
        for class in schema.classes.values() {
            for a in &class.attributes {
                all.push(&a.name);
            }
        }
        all.sort();
        for (i, n) in all.iter().enumerate() {
            rows.push((n, i));
        }
    }
    let mut by_class: BTreeMap<&str, Vec<(&Name, usize)>> = BTreeMap::new();
    for (name, id) in &rows {
        if let Some(owner) = name.owner() {
            by_class.entry(owner).or_default().push((name, *id));
        }
    }
    for (class, attrs) in by_class {
        let module = rust_module(class);
        writeln!(
            s,
            "    /// Attributes of `{class}`.\n    pub mod {module} {{\n        use super::AttrId;"
        )
        .unwrap();
        for (name, id) in attrs {
            let label = name.local.rsplit('.').next().unwrap_or("");
            writeln!(
                s,
                "        /// `{}`\n        pub const {}: AttrId = AttrId({id});",
                name.local,
                rust_const(label)
            )
            .unwrap();
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n\n");

    // Enumerations and their literals.
    s.push_str("/// Enumerations and their literals.\npub mod enums {\n    use super::{EnumId, EnumValueId};\n");
    let mut value_id: BTreeMap<&Name, usize> = BTreeMap::new();
    {
        let mut all: Vec<&Name> = Vec::new();
        for e in schema.enums.values() {
            for v in &e.values {
                all.push(&v.name);
            }
        }
        all.sort();
        for (i, n) in all.iter().enumerate() {
            value_id.insert(n, i);
        }
    }
    for (ei, e) in schema.enums.values().enumerate() {
        let module = rust_module(&e.name.local);
        writeln!(
            s,
            "    /// `{}`\n    pub mod {module} {{\n        use super::{{EnumId, EnumValueId}};\n        /// The enumeration itself.\n        pub const TYPE: EnumId = EnumId({ei});",
            e.name.local
        )
        .unwrap();
        for v in &e.values {
            writeln!(
                s,
                "        /// `{}`\n        pub const {}: EnumValueId = EnumValueId({});",
                v.name.local,
                rust_const(&v.label),
                value_id[&v.name]
            )
            .unwrap();
        }
        s.push_str("    }\n");
    }
    s.push_str("}\n");
    s
}

// ---------------------------------------------------------------------------
// Typed views
// ---------------------------------------------------------------------------

fn emit_views(schema: &Schema) -> String {
    let mut s = String::with_capacity(2 << 20);
    s.push_str(HEADER);
    s.push_str(
        "
//! Typed views over stored objects.
//!
//! A view is a zero-cost wrapper around an [`Object`](crate::object::Object) that gives
//! schema-checked, typed access to the attributes of one class. Views borrow rather than
//! own, so obtaining one never copies model data.

#![allow(clippy::all, non_upper_case_globals, non_snake_case)]

use crate::dataset::Dataset;
use crate::mrid::Mrid;
use crate::object::Object;
use crate::schema::{ClassId, EnumValueId};
use crate::view::{TypedView, TypedRef};

use super::names::{attributes as attrs, classes};

",
    );

    for class in schema.classes.values() {
        let ident = rust_type(&class.name.local);
        let class_const = rust_const(&class.name.local);
        let doc = doc_comment(class.comment.as_deref(), 0);
        writeln!(
            s,
            "{doc}#[derive(Clone, Copy, Debug)]\npub struct {ident}<'a>(pub &'a Object);\n"
        )
        .unwrap();

        writeln!(
            s,
            "impl<'a> TypedView<'a> for {ident}<'a> {{\n    const CLASS: ClassId = classes::{class_const};\n    #[inline]\n    fn from_object(o: &'a Object) -> Self {{ {ident}(o) }}\n    #[inline]\n    fn object(&self) -> &'a Object {{ self.0 }}\n}}\n"
        )
        .unwrap();

        writeln!(s, "impl<'a> {ident}<'a> {{").unwrap();
        writeln!(
            s,
            "    /// The object's master resource identifier.\n    #[inline]\n    pub fn mrid(&self) -> &'a Mrid {{ self.0.mrid() }}\n"
        )
        .unwrap();

        // Assign method names most-derived first, so a subclass attribute keeps the
        // plain name and a shadowed inherited one is qualified by its declaring class.
        // `mrid` is reserved for the identifier accessor emitted above.
        let mut taken: BTreeMap<String, ()> = BTreeMap::new();
        taken.insert("mrid".to_owned(), ());
        let attrs: Vec<_> = schema.all_attributes(&class.name);
        let mut methods: Vec<String> = vec![String::new(); attrs.len()];
        for (i, (owner, attr)) in attrs.iter().enumerate().rev() {
            let label = attr.name.local.rsplit('.').next().unwrap_or("");
            let mut method = rust_method(label);
            if taken.contains_key(&method) {
                method = format!("{}_{}", rust_module(&owner.name.local), rust_method(label));
            }
            // Still colliding (two classes, same names): fall back to a numbered form.
            if taken.contains_key(&method) {
                method = format!("{method}_{i}");
            }
            taken.insert(method.clone(), ());
            methods[i] = method;
        }

        for (i, (owner, attr)) in attrs.iter().enumerate() {
            let owner_mod = rust_module(&owner.name.local);
            let label = attr.name.local.rsplit('.').next().unwrap_or("");
            let const_name = rust_const(label);
            let path = format!("attrs::{owner_mod}::{const_name}");
            let doc = doc_comment(attr.comment.as_deref(), 1);
            emit_accessor(&mut s, schema, attr, &path, &methods[i], &doc);
        }
        s.push_str("}\n\n");
    }

    s
}

fn emit_accessor(
    s: &mut String,
    schema: &Schema,
    attr: &crate::ir::Attribute,
    path: &str,
    method: &str,
    doc: &str,
) {
    let many = attr.multiplicity.is_many();
    match &attr.kind {
        AttrKind::Primitive(p) => {
            let (ty, conv) = primitive_accessor(*p);
            if many {
                writeln!(
                    s,
                    "{doc}    pub fn {method}(&self) -> impl Iterator<Item = {ty}> + '_ {{\n        self.0.get_all({path}).iter().filter_map(|s| s.value.{conv})\n    }}\n"
                )
                .unwrap();
            } else {
                writeln!(
                    s,
                    "{doc}    #[inline]\n    pub fn {method}(&self) -> Option<{ty}> {{\n        self.0.get({path}).and_then(|v| v.{conv})\n    }}\n"
                )
                .unwrap();
            }
        }
        AttrKind::Datatype(d) => {
            let prim = schema
                .datatypes
                .get(d)
                .map(|dt| dt.value)
                .unwrap_or(Primitive::Float);
            let (ty, conv) = primitive_accessor(prim);
            let unit_doc = schema
                .datatypes
                .get(d)
                .map(|dt| {
                    let unit = dt.unit.as_deref().unwrap_or("none");
                    let mult = dt.multiplier.as_deref().unwrap_or("none");
                    if mult == "none" {
                        format!("    ///\n    /// Unit: `{unit}`.\n")
                    } else {
                        format!("    ///\n    /// Unit: `{unit}`, multiplier `{mult}`.\n")
                    }
                })
                .unwrap_or_default();
            if many {
                writeln!(
                    s,
                    "{doc}{unit_doc}    pub fn {method}(&self) -> impl Iterator<Item = {ty}> + '_ {{\n        self.0.get_all({path}).iter().filter_map(|s| s.value.{conv})\n    }}\n"
                )
                .unwrap();
            } else {
                writeln!(
                    s,
                    "{doc}{unit_doc}    #[inline]\n    pub fn {method}(&self) -> Option<{ty}> {{\n        self.0.get({path}).and_then(|v| v.{conv})\n    }}\n"
                )
                .unwrap();
            }
        }
        AttrKind::Enumeration(_) => {
            if many {
                writeln!(
                    s,
                    "{doc}    pub fn {method}(&self) -> impl Iterator<Item = EnumValueId> + '_ {{\n        self.0.get_all({path}).iter().filter_map(|s| s.value.as_enum())\n    }}\n"
                )
                .unwrap();
            } else {
                writeln!(
                    s,
                    "{doc}    #[inline]\n    pub fn {method}(&self) -> Option<EnumValueId> {{\n        self.0.get({path}).and_then(|v| v.as_enum())\n    }}\n"
                )
                .unwrap();
            }
        }
        AttrKind::Association { target, .. } => {
            let target_ty = rust_type(&target.local);
            if many {
                writeln!(
                    s,
                    "{doc}    pub fn {method}(&self) -> impl Iterator<Item = TypedRef<{target_ty}<'static>>> + '_ {{\n        self.0.get_all({path}).iter().filter_map(|s| s.value.as_reference()).map(|m| TypedRef::new(m.clone()))\n    }}\n"
                )
                .unwrap();
                // Resolving convenience that walks the dataset.
                writeln!(
                    s,
                    "    /// Resolve every `{}` through `dataset`, skipping unresolved references.\n    pub fn {method}_in<'d>(&self, dataset: &'d Dataset) -> impl Iterator<Item = {target_ty}<'d>> + 'd {{\n        let mrids: Vec<Mrid> = self.0.get_all({path}).iter().filter_map(|s| s.value.as_reference().cloned()).collect();\n        mrids.into_iter().filter_map(move |m| dataset.by_mrid(&m).map(|o| {target_ty}(o)))\n    }}\n",
                    attr.label
                )
                .unwrap();
            } else {
                writeln!(
                    s,
                    "{doc}    #[inline]\n    pub fn {method}(&self) -> Option<TypedRef<{target_ty}<'static>>> {{\n        self.0.get({path}).and_then(|v| v.as_reference()).map(|m| TypedRef::new(m.clone()))\n    }}\n"
                )
                .unwrap();
                writeln!(
                    s,
                    "    /// Resolve `{}` through `dataset`.\n    #[inline]\n    pub fn {method}_in<'d>(&self, dataset: &'d Dataset) -> Option<{target_ty}<'d>> {{\n        let m = self.0.get({path})?.as_reference()?;\n        dataset.by_mrid(m).map(|o| {target_ty}(o))\n    }}\n",
                    attr.label
                )
                .unwrap();
            }
        }
    }
}

fn primitive_accessor(p: Primitive) -> (&'static str, &'static str) {
    match p {
        Primitive::Boolean => ("bool", "as_bool()"),
        Primitive::Integer => ("i64", "as_i64()"),
        Primitive::Float | Primitive::Decimal => ("f64", "as_f64()"),
        _ => ("&str", "as_str()"),
    }
}

// ---------------------------------------------------------------------------
// Formatting helpers
// ---------------------------------------------------------------------------

fn primitive(p: Primitive) -> &'static str {
    match p {
        Primitive::String => "Primitive::String",
        Primitive::Integer => "Primitive::Integer",
        Primitive::Float => "Primitive::Float",
        Primitive::Decimal => "Primitive::Decimal",
        Primitive::Boolean => "Primitive::Boolean",
        Primitive::Date => "Primitive::Date",
        Primitive::DateTime => "Primitive::DateTime",
        Primitive::MonthDay => "Primitive::MonthDay",
        Primitive::Time => "Primitive::Time",
        Primitive::Duration => "Primitive::Duration",
        Primitive::Uri => "Primitive::Uri",
    }
}

fn mult(m: Multiplicity) -> String {
    match m {
        Multiplicity::Optional => "Mult::Optional".to_owned(),
        Multiplicity::Required => "Mult::Required".to_owned(),
        Multiplicity::Many => "Mult::Many".to_owned(),
        Multiplicity::ManyRequired => "Mult::ManyRequired".to_owned(),
        Multiplicity::Bounded { min, max } => format!("Mult::Bounded {{ min: {min}, max: {max} }}"),
    }
}

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn opt_quote(s: Option<&str>) -> String {
    match s {
        Some(v) => format!("Some({})", quote(v)),
        None => "None".to_owned(),
    }
}

/// Render a schema comment as a rustdoc block at the given indent level.
fn doc_comment(comment: Option<&str>, indent: usize) -> String {
    let Some(c) = comment.filter(|c| !c.is_empty()) else {
        return String::new();
    };
    let pad = "    ".repeat(indent);
    let mut out = String::new();
    // Keep documentation bounded; the standard's longest comments run to pages.
    for line in c.lines().take(24) {
        out.push_str(&pad);
        out.push_str("/// ");
        out.push_str(&escape_doc(line));
        out.push('\n');
    }
    out
}

/// Neutralize constructs in the standard's own prose that rustdoc would reject.
///
/// Class documentation is copied verbatim from IEC 61970-301, which uses brackets and
/// bare URLs freely. Brackets would be parsed as intra-doc links and bare URLs trip
/// `rustdoc::bare_urls`, so both are made inert.
fn escape_doc(s: &str) -> String {
    let cleaned = s.replace('\r', "").replace('[', "\\[").replace(']', "\\]");
    autolink(cleaned.trim())
}

/// Wrap bare `http(s)://` URLs in angle brackets so rustdoc renders them as links.
fn autolink(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(start) = find_url(rest) {
        out.push_str(&rest[..start]);
        let tail = &rest[start..];
        // A URL runs to whitespace; trailing sentence punctuation is not part of it.
        let mut end = tail.find(char::is_whitespace).unwrap_or(tail.len());
        while end > 0 && matches!(tail.as_bytes()[end - 1], b'.' | b',' | b';' | b':' | b')') {
            end -= 1;
        }
        out.push('<');
        out.push_str(&tail[..end]);
        out.push('>');
        rest = &tail[end..];
    }
    out.push_str(rest);
    out
}

fn find_url(s: &str) -> Option<usize> {
    let http = s.find("http://");
    let https = s.find("https://");
    match (http, https) {
        (Some(a), Some(b)) => Some(a.min(b)),
        (Some(a), None) => Some(a),
        (None, Some(b)) => Some(b),
        (None, None) => None,
    }
}

/// Rust keywords that cannot be used as bare identifiers.
const KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "union",
    "unsafe", "use", "where", "while", "async", "await", "box", "final", "macro", "override",
    "priv", "try", "typeof", "unsized", "virtual", "yield", "abstract", "become", "do",
];

fn sanitize(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        if c.is_ascii_alphanumeric() {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

/// Constant name mirroring the CIM identifier exactly.
///
/// CIM names are the stable, documented surface of the standard, and transforming them
/// loses information: `UnitMultiplier.M` (mega) and `UnitMultiplier.m` (milli) both
/// upper-case to `M`. Keeping the original spelling makes every generated identifier
/// unambiguous and lets a reader of IEC 61970-301 find it without guessing a mapping.
fn rust_const(s: &str) -> String {
    let out = sanitize(s);
    if KEYWORDS.contains(&out.as_str()) {
        format!("{out}_")
    } else {
        out
    }
}

/// snake_case module name.
fn rust_module(s: &str) -> String {
    let out = snake_case(&sanitize(s));
    if KEYWORDS.contains(&out.as_str()) {
        format!("{out}_")
    } else {
        out
    }
}

/// snake_case method name for the public view API, where Rust idiom applies.
fn rust_method(s: &str) -> String {
    rust_module(s)
}

/// Convert a CIM camel/Pascal identifier to snake_case.
///
/// Runs of capitals are kept together, so `mRID` becomes `m_rid` and `ACLineSegment`
/// becomes `ac_line_segment` rather than `a_c_line_segment`.
fn snake_case(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::with_capacity(s.len() + 4);
    for (i, &c) in chars.iter().enumerate() {
        if c == '_' {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            continue;
        }
        if c.is_ascii_uppercase() && i > 0 {
            let prev = chars[i - 1];
            let next_lower = chars.get(i + 1).is_some_and(|n| n.is_ascii_lowercase());
            // Boundary after a lowercase/digit, or before the tail of an acronym.
            let boundary = prev.is_ascii_lowercase()
                || prev.is_ascii_digit()
                || (prev.is_ascii_uppercase() && next_lower);
            if boundary && !out.ends_with('_') {
                out.push('_');
            }
        }
        out.push(c.to_ascii_lowercase());
    }
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    out
}

/// PascalCase type name; CIM class names are already PascalCase.
fn rust_type(s: &str) -> String {
    let out = sanitize(s);
    if KEYWORDS.contains(&out.as_str()) {
        format!("{out}_")
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constants_mirror_the_standards_own_spelling() {
        // Transforming CIM names loses information: `UnitMultiplier.M` (mega) and
        // `UnitMultiplier.m` (milli) both upper-case to `M`.
        assert_eq!(rust_const("ACLineSegment"), "ACLineSegment");
        assert_eq!(rust_const("mRID"), "mRID");
        assert_eq!(rust_const("nominalVoltage"), "nominalVoltage");
        assert_ne!(rust_const("M"), rust_const("m"));
        assert_eq!(rust_const("M"), "M");
        assert_eq!(rust_const("m"), "m");
    }

    #[test]
    fn method_names_are_snake_case_with_acronyms_kept_together() {
        assert_eq!(rust_method("ACLineSegment"), "ac_line_segment");
        assert_eq!(rust_method("mRID"), "m_rid");
        assert_eq!(rust_method("nominalVoltage"), "nominal_voltage");
        assert_eq!(rust_method("r"), "r");
        assert_eq!(rust_method("b0ch"), "b0ch");
        assert_eq!(rust_method("BaseVoltage"), "base_voltage");
        // Reserved words are escaped so `SynchronousMachine.type` stays usable.
        assert_eq!(rust_method("type"), "type_");
    }

    #[test]
    fn keywords_and_digits_are_escaped() {
        assert_eq!(rust_module("type"), "type_");
        assert_eq!(rust_method("ref"), "ref_");
        assert!(sanitize("3phase").starts_with('_'));
    }

    #[test]
    fn doc_escaping_neutralizes_brackets() {
        assert_eq!(escape_doc("see [IEC]"), "see \\[IEC\\]");
    }
}
